### ISSUE TITLE
Styling the Output

### ISSUE THREAD

**Issue by syncalvo** [OliverPaljak/JSDynamicFormContent#1]
Thank you for the this Javascript.  How would I go about applying styles to the output?

**Comment by OliverPaljak** [comment]
Use CSS :D

Probably the most simplest way would be to modify the `getFormattedFormContent()` function.
For example:
```js
getFormattedFormContent(){
    var formContent = "";

    var formData = this.getFormData();

    for(var input in formData){
        //Add a div with class, which value is equal to the input's name
        formContent += "<div class=\"" + input +"\">";   
        formContent += "<b>" + input + "</b>: " + formData[input];
        formContent += "</div>";
    }

    return formContent;
}
```

Then add CSS to the page:
```css
.input-1-name{
    /*Some style here*/
}
.input-2-name{
    /*Some style here*/
}
/*And so on*/
```

You don't have to style every input separately - you can also add just one class to the parent element (in this case div element) and style them all at once:
```js
getFormattedFormContent(){
    var formContent = "";

    var formData = this.getFormData();

    for(var input in formData){
        formContent += "<div class=\"someclass\">"; //Add a div with class "someclass"
        formContent += "<b>" + input + "</b>: " + formData[input];
        formContent += "</div>";
    }

    return formContent;
}
```

```css
.someclass{
    /*Some style*/
}
```

For the sake of simplicity I used the function from dynamic-form-content-dev.js - probably you want to modify the dynamic-form-content-prod.js and also minify it. Or alternatively, recompile modified dynamic-form-content-dev.js with babel.
